### PR TITLE
Update runtime

### PR DESCRIPTION
**Pull request by yakushabb**
Update out-of-date runtime

### CODE REVIEW

**Comment by mbasaglia** [comment]
Not sure why the linting failed if it was fine before :thinking:

**Comment by ghost** [comment]
My guest, metainfo file does not contain a launchable tag that point the desktop file.

https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-launchable

resim

**Comment by ghost** [comment]
Sorry, also developer name or developer blok is missign

https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#name-summary-and-developer-name

**Comment by ghost** [comment]
@mbasaglia Could you review it.

**Pull request merged**
